### ISSUE TITLE
Difficulties Setting Up Environment: No Module named Pythonosc

### ISSUE THREAD

**Issue by jgazzara1** [BarakChamo/OpenVR-OSC#1]
Hello, 

I am a student currently trying to use this software to take the Yaw Pitch and Roll values from my VR headset and sending them to a different device.

I am not as familiar with the VR development environment, but I have Python experience. When I try to run this software, I get "no module named pythonosc" even though the installation requirement is already satisfied when I try to use Pip. 

Does running this software require more development environments than I think? Do I need to have Unity Hub installed? Do I need to add more software from other GitHub pages to the OpenVR-OSC-master folder?

Any tips for getting the environment setup would be greatly appreciated. Thanks.

**Comment by orgicus** [comment]
Hi,

Just spotted this issue now.
Have you tried installing the required packges ?
e.g. using Terminal/Command Prompt, `cd` into your clone of OpenVR-OSC then
`pip install -r requirements.txt` (as the [installation step recommends](https://github.com/BarakChamo/OpenVR-OSC#installation))

>Does running this software require more development environments than I think? 

Not 100% sure I understand what you mean by that. If it relates to [Python virtual environments](https://docs.python.org/3/tutorial/venv.html) it might be a good idea so you avoid clashes with different versions of same libraries and overall keeping your global pip packages list clean.

>Do I need to have Unity Hub installed? 

I don't think so, I didn't need Unity installed at all to run this.

>Do I need to add more software from other GitHub pages to the OpenVR-OSC-master folder?

The repo uses [`triad_openvr`](https://github.com/TriadSemi/triad_openvr) repo as submodule. Ideally you would've cloned this repo recursively (e.g. using passing `--recurse-submodules` to `git clone`). Alternatively, if you didn't clone the repo recursively, you can still get the submodule by running git `git submodule update --recursive --remote` (after you've `cd`-ed into your clone of this repo of course). (Simply downloading the repo as .zip doesn't)

You will need SteamVR installed of course. (Additionally, if you plan on not using an HMD, you need to follow [this lengthy guide](http://web.archive.org/web/20190415015339/http://help.triadsemi.com/steamvr-tracking/steamvr-tracking-without-an-hmd) (bare in mind this is a cached page via WayBack Machine so most links won't work, but for some, if you hover over them you'll notice in the status bar of your browser where they point to and you tweak them to be original links (not archive.org prefixed ones))

**Comment by jgazzara1** [comment]
Appreciate the detailed response. Unfortunately, this project is long over. We ended up using an external gyroscope attached to the headset to get these values. If I end up picking this up again in the future, I will use your guide. Thanks!
